name: Hello world
on:
  push:
    branches: [main]
jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: pwd
        run: |
          echo "step pwd"
          pwd
      - name: ls
        run: ls -la
      - name: build frontend
        run: |
          ls
          cd frontend
          npm install
          